let snap={deployments:[],health:[],events:[],config:{}}, providerSummaries=[];
let editor={mode:'add',originalId:'',provider:null,detected:[],selected:new Set(),modelMeta:new Map(),secretDirty:false,secretSource:'none'};
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
let adminKey=sessionStorage.getItem('nexaroute_admin_key')||'';
async function apiFetch(url,opt={}){
  opt={...opt,headers:{...(opt.headers||{})}};
  if(adminKey)opt.headers['x-admin-key']=adminKey;
  let r=await window.fetch(url,opt);
  if(r.status===401){
    const k=prompt('Admin API key required');
    if(k!==null){adminKey=k.trim();sessionStorage.setItem('nexaroute_admin_key',adminKey);opt.headers['x-admin-key']=adminKey;r=await window.fetch(url,opt)}
  }
  return r;
}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(url,opt={}){const r=await apiFetch(url,opt);let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b?.error?.message||`HTTP ${r.status}`);return b}
function toast(m,bad=false){const t=$('#toast');t.textContent=m;t.className='toast show '+(bad?'bad':'');clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast',2500)}

$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');$('#title').textContent=b.textContent==='Overview'?'Routing Overview':b.textContent;if(b.dataset.tab==='settings')fillRuntimeSettings()});
$('#probeBtn').onclick=async()=>{try{$('#probeBtn').disabled=true;$('#probeBtn').textContent='Probing…';const d=await api('/admin/api/probe?wait=1',{method:'POST'});const r=d.result||{};toast(`Probe complete: ${r.passed||0}/${r.total||0} passed${r.skipped_cooldown?`, ${r.skipped_cooldown} cooldown`:''}`,!!r.failed);await refresh()}catch(e){toast(e.message,true)}finally{$('#probeBtn').disabled=false;$('#probeBtn').textContent='Probe all models'}};
$('#adminKey').value=adminKey;$('#saveAdminKey').onclick=()=>{adminKey=$('#adminKey').value.trim();sessionStorage.setItem('nexaroute_admin_key',adminKey);toast('Admin key saved for this browser session')};
$('#toggleAdminKey').onclick=()=>toggleSecret('#adminKey','#toggleAdminKey');
function intVal(id,fallback,min=0){const n=parseInt($(id).value,10);return Number.isFinite(n)?Math.max(min,n):fallback}
function fillRuntimeSettings(){const r=snap.config?.routing||{},p=snap.config?.probe||{};$('#rtStrategy').value=r.strategy||'adaptive_round_robin';$('#rtFallback').checked=r.fallback_on_unknown_model!==false;$('#rtAttempts').value=r.max_attempts||4;$('#rtFailureThreshold').value=r.failure_threshold||5;$('#rtCooldown').value=r.cooldown_seconds||3600;$('#rtTimeout').value=r.request_timeout_ms||120000;$('#rtBackoff').value=Number.isFinite(r.retry_backoff_ms)?r.retry_backoff_ms:150;$('#rtRetryAfter').value=r.max_retry_after_seconds||60;$('#prEnabled').checked=p.enabled!==false;$('#prOnStart').checked=!!p.on_start;$('#prInterval').value=p.interval_seconds||120;$('#prTimeout').value=p.timeout_ms||8000;$('#prTokens').value=p.max_tokens||1;$('#prConcurrency').value=p.concurrency||16}
$('#saveRuntimeSettings').onclick=async()=>{const old=snap.config||{},r=old.routing||{},p=old.probe||{};const body={routing:{...r,strategy:$('#rtStrategy').value,fallback_on_unknown_model:$('#rtFallback').checked,max_attempts:intVal('#rtAttempts',4,1),failure_threshold:intVal('#rtFailureThreshold',5,1),cooldown_seconds:intVal('#rtCooldown',3600,1),request_timeout_ms:intVal('#rtTimeout',120000,100),retry_backoff_ms:intVal('#rtBackoff',150,0),max_retry_after_seconds:intVal('#rtRetryAfter',60,1)},probe:{...p,enabled:$('#prEnabled').checked,on_start:$('#prOnStart').checked,interval_seconds:intVal('#prInterval',120,1),timeout_ms:intVal('#prTimeout',8000,100),max_tokens:intVal('#prTokens',1,1),concurrency:intVal('#prConcurrency',16,1)}};try{$('#saveRuntimeSettings').disabled=true;await api('/admin/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Runtime settings saved and reloaded');await refresh();fillRuntimeSettings()}catch(e){toast(e.message,true)}finally{$('#saveRuntimeSettings').disabled=false}};

function healthMap(){const m={};for(const h of snap.health||[])m[h.deployment]=h;return m}
function render(){const h=healthMap(),ds=snap.deployments||[];const sl=$('#routerStrategyLabel');if(sl)sl.textContent=snap.config?.routing?.strategy||'adaptive_round_robin';$('#sDeploy').textContent=ds.length;let ok=0,cd=0,ls=[];for(const d of ds){const x=h[d.id]||{};if(x.status==='healthy')ok++;if(x.status==='cooldown')cd++;if(x.ewma_latency_ms)ls.push(x.ewma_latency_ms)}$('#sHealthy').textContent=ok;$('#sCooldown').textContent=cd;$('#sLatency').textContent=ls.length?Math.round(ls.reduce((a,b)=>a+b,0)/ls.length)+' ms':'—';renderRing(ds,h);renderProviders(h);renderModels(ds,h);renderEvents();$('#settingsJson').textContent=JSON.stringify(snap.config||{},null,2)}
function renderRing(ds,h){const ring=$('#ring');[...ring.querySelectorAll('.node')].forEach(x=>x.remove());const svg=$('#links');svg.innerHTML='';const shown=ds.slice(0,100),W=ring.clientWidth,H=ring.clientHeight,cx=W/2,cy=H/2;ring.classList.toggle('dense',shown.length>24);const ringCount=Math.max(1,Math.min(4,Math.ceil(shown.length/25)));shown.forEach((d,i)=>{const ri=Math.floor(i/25),start=ri*25,count=Math.min(25,shown.length-start),pos=i-start,a=Math.PI*2*pos/Math.max(count,1)-Math.PI/2;const frac=ringCount===1?1:(ri+1)/ringCount;const rx=shown.length>24?110+frac*Math.min(W*.34,300):Math.min(W*.38,360),ry=shown.length>24?60+frac*Math.min(H*.31,210):Math.min(H*.36,190),x=cx+Math.cos(a)*rx,y=cy+Math.sin(a)*ry,st=(h[d.id]||{}).status||'unknown';const n=document.createElement('div');n.className='node '+st;n.style.left=x+'px';n.style.top=y+'px';n.title=`${d.model} • ${d.provider_name||d.provider_id} • ${st}`;n.innerHTML=`<strong>${esc(d.model)}</strong><small>${esc(d.provider_name||d.provider_id)}</small><span class="badge">${esc(st)}</span>`;ring.appendChild(n);const l=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v] of Object.entries({x1:cx,y1:cy,x2:x,y2:y,stroke:st==='healthy'?'#214d42':st==='cooldown'?'#512832':st==='degraded'?'#665126':'#26384f','stroke-width':1,'stroke-dasharray':'3 5'}))l.setAttribute(k,v);svg.appendChild(l)});if(ds.length>100){const n=document.createElement('div');n.className='node degraded';n.style.left=cx+'px';n.style.top=(H-28)+'px';n.innerHTML=`<strong>+${ds.length-100} more</strong><small>See Models table</small>`;ring.appendChild(n)}}
function renderProviders(h){$('#providerGrid').innerHTML=providerSummaries.map(p=>{const ds=(snap.deployments||[]).filter(d=>d.provider_id===p.id),ok=ds.filter(d=>(h[d.id]||{}).status==='healthy').length;return `<article class="provider-card"><div class="provider-card-top"><div class="provider-mark">${esc((p.name||p.id).slice(0,1).toUpperCase())}</div><div class="provider-copy"><h3>${esc(p.name||p.id)}</h3><p>${esc(p.type)} · ${p.model_count} models</p></div><span class="pill ${p.enabled?'on':'off'}">${p.enabled?'Enabled':'Disabled'}</span></div><div class="provider-url">${esc(p.base_url)}</div><div class="provider-meta"><span>${p.has_secret?`${p.credential_count||1} credential(s)`:'No credential'}</span><span>${ok}/${ds.length} healthy</span></div><button class="edit-provider btn secondary" data-id="${esc(p.id)}">Edit provider</button></article>`}).join('')||'<div class="empty-state"><strong>No providers yet.</strong><span>Add an OpenAI-compatible or Anthropic-compatible upstream.</span></div>';$$('.edit-provider').forEach(b=>b.onclick=()=>openEdit(b.dataset.id))}
function renderModels(ds,h){$('#modelRows').innerHTML=ds.map(d=>{const x=h[d.id]||{status:'unknown'};return `<tr><td>${esc(d.id)}</td><td>${esc(d.provider_id)}</td><td>${esc(d.model)}</td><td><span class="status ${esc(x.status)}">${esc(x.status)}</span></td><td>${x.ewma_latency_ms?Math.round(x.ewma_latency_ms)+' ms':'—'}</td><td>${x.consecutive_failures||0}</td></tr>`}).join('')}
function renderEvents(){const es=(snap.events||[]).slice().reverse().slice(0,100);$('#eventList').innerHTML=es.map(e=>`<div class="event"><time>${new Date(e.time).toLocaleTimeString()}</time><span class="kind">${esc(e.kind)}</span><span>${esc((e.deployment||'')+' '+(e.message||''))}</span><span title="${esc(e.request_id||'')}">${e.request_id?esc(e.request_id.slice(-10)):''}</span><span>${e.latency_ms?e.latency_ms+' ms':''}</span></div>`).join('')||'<p>No events yet.</p>'}
async function refresh(){try{const [s,p]=await Promise.all([api('/admin/api/snapshot'),api('/admin/api/providers')]);snap=s;providerSummaries=p.providers||[];$('#apiState').textContent='● connected';render()}catch(e){$('#apiState').textContent='● disconnected'}}
async function tick(){await refresh();setTimeout(tick,1800)}window.addEventListener('resize',render);

function emptyProvider(){return{id:'',name:'',type:'openai_compatible',base_url:'',api_key:'',api_key_env:'',credentials:[],auth_mode:'bearer',headers:{},forward_headers:[],proxy_url:'',chat_path:'/v1/chat/completions',messages_path:'/v1/messages',models_path:'/v1/models',count_tokens_path:'/v1/messages/count_tokens',max_concurrency:32,stream_idle_timeout_seconds:180,enabled:true,models:[]}}
function modal(open){$('#providerModal').classList.toggle('open',open);$('#providerModal').setAttribute('aria-hidden',open?'false':'true');document.body.classList.toggle('modal-open',open)}
function toggleSecret(i,b){const el=$(i);el.type=el.type==='password'?'text':'password';$(b).textContent=el.type==='password'?'Show':'Hide'}
const providerPresets={
  custom:null,
  chat2api:{name:'Chat2API',id:'chat2api',type:'openai_compatible',base:'http://127.0.0.1:5000/v1',auth:'bearer'},
  anthropic:{name:'Anthropic',id:'anthropic',type:'anthropic_compatible',base:'https://api.anthropic.com',auth:'x-api-key'},
  openai:{name:'OpenAI',id:'openai',type:'openai_compatible',base:'https://api.openai.com/v1',auth:'bearer'},
  openrouter:{name:'OpenRouter',id:'openrouter',type:'openai_compatible',base:'https://openrouter.ai/api/v1',auth:'bearer'},
  deepseek:{name:'DeepSeek',id:'deepseek',type:'openai_compatible',base:'https://api.deepseek.com',auth:'bearer'},
  groq:{name:'Groq',id:'groq',type:'openai_compatible',base:'https://api.groq.com/openai/v1',auth:'bearer'},
  together:{name:'Together AI',id:'together',type:'openai_compatible',base:'https://api.together.xyz/v1',auth:'bearer'},
  mistral:{name:'Mistral',id:'mistral',type:'openai_compatible',base:'https://api.mistral.ai/v1',auth:'bearer'},
  xai:{name:'xAI',id:'xai',type:'openai_compatible',base:'https://api.x.ai/v1',auth:'bearer'},
  ollama:{name:'Ollama',id:'ollama',type:'openai_compatible',base:'http://127.0.0.1:11434/v1',auth:'none'}
};
function applyPreset(k){const p=providerPresets[k];if(!p)return;if(editor.mode==='add'){if(!$('#pName').value.trim())$('#pName').value=p.name;if(!$('#pId').value.trim())$('#pId').value=p.id}$('#pType').value=p.type;$('#pBase').value=p.base;$('#pAuth').value=p.auth;$('#pChatPath').value='/v1/chat/completions';$('#pMessagesPath').value='/v1/messages';$('#pModelsPath').value='/v1/models';$('#pCountPath').value='/v1/messages/count_tokens'}

$('#addProviderBtn').onclick=()=>{editor={mode:'add',originalId:'',provider:emptyProvider(),detected:[],selected:new Set(),modelMeta:new Map(),secretDirty:true,secretSource:'none'};fillForm();modal(true)};$('#closeProviderModal').onclick=()=>modal(false);$('#cancelProviderBtn').onclick=()=>modal(false);$$('[data-close-modal]').forEach(x=>x.onclick=()=>modal(false));$('#togglePKey').onclick=()=>toggleSecret('#pKey','#togglePKey');$('#pKey').oninput=()=>editor.secretDirty=true;$('#pKeyEnv').oninput=()=>editor.secretDirty=true;$('#pCredentials').oninput=()=>editor.secretDirty=true;
$('#pPreset').onchange=()=>applyPreset($('#pPreset').value);
$('#pType').onchange=()=>{const a=$('#pAuth');if($('#pType').value==='anthropic_compatible'&&a.value==='bearer')a.value='x-api-key';if($('#pType').value==='openai_compatible'&&a.value==='x-api-key')a.value='bearer'};
async function openEdit(id){try{const d=await api('/admin/api/providers/'+encodeURIComponent(id)+'?reveal=1'),p=d.provider;p.api_key=d.resolved_api_key||p.api_key||'';editor={mode:'edit',originalId:id,provider:p,detected:(p.models||[]).map(m=>m.model),selected:new Set((p.models||[]).map(m=>m.model)),modelMeta:new Map((p.models||[]).map(m=>[m.model,m])),secretDirty:false,secretSource:d.secret_source||'none'};fillForm();modal(true)}catch(e){toast(e.message,true)}}
function fillForm(){const p=editor.provider;$('#pPreset').value='custom';$('#providerFormTitle').textContent=editor.mode==='edit'?'Edit provider':'Add provider';$('#deleteProviderBtn').classList.toggle('hidden',editor.mode!=='edit');$('#pName').value=p.name||'';$('#pId').value=p.id||'';$('#pId').disabled=editor.mode==='edit';$('#pType').value=p.type||'openai_compatible';$('#pBase').value=p.base_url||'';$('#pAuth').value=p.auth_mode||'bearer';$('#pEnabled').checked=p.enabled!==false;$('#pKey').value=p.api_key||'';$('#pKey').type='password';$('#togglePKey').textContent='Show';$('#pKeyEnv').value=p.api_key_env||'';$('#pHeaders').value=Object.keys(p.headers||{}).length?JSON.stringify(p.headers,null,2):'';$('#pProxy').value=p.proxy_url||'';$('#pConcurrency').value=p.max_concurrency||32;$('#pStreamIdle').value=p.stream_idle_timeout_seconds||180;$('#pChatPath').value=p.chat_path||'/v1/chat/completions';$('#pMessagesPath').value=p.messages_path||'/v1/messages';$('#pModelsPath').value=p.models_path||'/v1/models';$('#pCountPath').value=p.count_tokens_path||'/v1/messages/count_tokens';$('#pForwardHeaders').value=(p.forward_headers||[]).join(', ');$('#pCredentials').value=(p.credentials||[]).length?JSON.stringify(p.credentials,null,2):'';const first=(p.models||[])[0]||{};const caps=first.capabilities||{streaming:true,tools:true,vision:false,reasoning:false};$('#pAliases').value='';$('#pCapStreaming').checked=caps.streaming!==false;$('#pCapTools').checked=caps.tools!==false;$('#pCapVision').checked=!!caps.vision;$('#pCapReasoning').checked=!!caps.reasoning;$('#secretSource').textContent=editor.mode==='edit'?`saved source: ${editor.secretSource}`:'';$('#discoverStatus').textContent='';$('#testResults').innerHTML='';renderPicker()}
function slug(s){return s.toLowerCase().trim().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'model'}
function defaultModelMeta(m,i=0){return{id:slug(m),model:m,aliases:$('#pAliases').value.split(',').map(x=>x.trim()).filter(Boolean),enabled:true,priority:i,weight:1,capabilities:{streaming:$('#pCapStreaming').checked,tools:$('#pCapTools').checked,vision:$('#pCapVision').checked,reasoning:$('#pCapReasoning').checked}}}
function ensureModelMeta(m,i=0){if(!editor.modelMeta.has(m))editor.modelMeta.set(m,defaultModelMeta(m,i));const x=editor.modelMeta.get(m);x.capabilities=x.capabilities||{streaming:true,tools:true,vision:false,reasoning:false};if(!Array.isArray(x.aliases))x.aliases=[];if(!Number.isFinite(x.priority))x.priority=i;if(!Number.isFinite(x.weight)||x.weight<=0)x.weight=1;return x}
function readForm(){let hs={};const raw=$('#pHeaders').value.trim();if(raw){try{hs=JSON.parse(raw)}catch{throw new Error('Extra headers must be valid JSON')}}let creds=[];const cr=$('#pCredentials').value.trim();if(cr){try{creds=JSON.parse(cr);if(!Array.isArray(creds))throw new Error()}catch{throw new Error('Credential pool must be a JSON array')}}const models=[...editor.selected].map((m,i)=>{const x=ensureModelMeta(m,i),c=x.capabilities||{};return{id:x.id||slug(m),model:m,aliases:[...new Set((x.aliases||[]).map(v=>String(v).trim()).filter(Boolean))],enabled:x.enabled!==false,priority:Number.isFinite(Number(x.priority))?Number(x.priority):i,weight:Number(x.weight)>0?Number(x.weight):1,capabilities:{streaming:c.streaming!==false,tools:c.tools!==false,vision:!!c.vision,reasoning:!!c.reasoning}}});const p={id:$('#pId').value.trim(),name:$('#pName').value.trim(),type:$('#pType').value,base_url:$('#pBase').value.trim(),api_key:$('#pKey').value,api_key_env:$('#pKeyEnv').value.trim(),credentials:creds,auth_mode:$('#pAuth').value,headers:hs,forward_headers:$('#pForwardHeaders').value.split(',').map(x=>x.trim()).filter(Boolean),proxy_url:$('#pProxy').value.trim(),chat_path:$('#pChatPath').value.trim(),messages_path:$('#pMessagesPath').value.trim(),models_path:$('#pModelsPath').value.trim(),count_tokens_path:$('#pCountPath').value.trim(),max_concurrency:Math.max(1,parseInt($('#pConcurrency').value||'32',10)),stream_idle_timeout_seconds:Math.max(10,parseInt($('#pStreamIdle').value||'180',10)),enabled:$('#pEnabled').checked,models};if(!p.id)throw new Error('Internal ID is required');if(!p.name)p.name=p.id;if(!p.base_url)throw new Error('Base URL is required');return p}
function payload(p){return{provider:p,preserve_secret:editor.mode==='edit'&&!editor.secretDirty,test_models:[...editor.selected]}}
function renderPicker(){const all=[...new Set([...editor.detected,...editor.selected])];for(const [i,m] of all.entries())ensureModelMeta(m,i);$('#modelPicker').innerHTML=all.length?all.map((m,i)=>{const x=ensureModelMeta(m,i),c=x.capabilities||{};return `<div class="model-option"><div class="model-option-head"><input class="model-select" type="checkbox" data-model="${esc(m)}" ${editor.selected.has(m)?'checked':''}><strong>${esc(m)}</strong></div><div class="model-meta-grid"><label>Aliases<input data-model="${esc(m)}" data-meta="aliases" value="${esc((x.aliases||[]).join(', '))}" placeholder="coding, auto"></label><label>Priority<input data-model="${esc(m)}" data-meta="priority" type="number" value="${Number.isFinite(Number(x.priority))?Number(x.priority):i}"></label><label>Weight<input data-model="${esc(m)}" data-meta="weight" type="number" min="0.01" step="0.1" value="${Number(x.weight)>0?Number(x.weight):1}"></label></div><div class="model-cap-row"><label><input data-model="${esc(m)}" data-cap="streaming" type="checkbox" ${c.streaming!==false?'checked':''}>Streaming</label><label><input data-model="${esc(m)}" data-cap="tools" type="checkbox" ${c.tools!==false?'checked':''}>Tools</label><label><input data-model="${esc(m)}" data-cap="vision" type="checkbox" ${c.vision?'checked':''}>Vision</label><label><input data-model="${esc(m)}" data-cap="reasoning" type="checkbox" ${c.reasoning?'checked':''}>Reasoning</label></div></div>`}).join(''):'<div class="model-empty">No models selected yet.</div>';$$('#modelPicker .model-select').forEach(x=>x.onchange=()=>x.checked?editor.selected.add(x.dataset.model):editor.selected.delete(x.dataset.model));$$('#modelPicker [data-meta]').forEach(x=>x.oninput=()=>{const m=x.dataset.model,meta=ensureModelMeta(m);if(x.dataset.meta==='aliases')meta.aliases=x.value.split(',').map(v=>v.trim()).filter(Boolean);else if(x.dataset.meta==='priority')meta.priority=parseInt(x.value||'0',10);else if(x.dataset.meta==='weight')meta.weight=Math.max(.01,parseFloat(x.value||'1'))});$$('#modelPicker [data-cap]').forEach(x=>x.onchange=()=>{const meta=ensureModelMeta(x.dataset.model);meta.capabilities=meta.capabilities||{};meta.capabilities[x.dataset.cap]=x.checked})}
$('#addModelBtn').onclick=()=>{const m=$('#manualModel').value.trim();if(!m)return;editor.detected=[...new Set([...editor.detected,m])];editor.selected.add(m);ensureModelMeta(m,editor.detected.length-1);$('#manualModel').value='';renderPicker()};$('#manualModel').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#addModelBtn').click()}};
$('#discoverBtn').onclick=async()=>{try{const p=readForm();$('#discoverBtn').disabled=true;$('#discoverStatus').textContent='Detecting…';const d=await api('/admin/api/provider-discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(p))});if(!d.ok)throw new Error(d.error||'No models discovered');editor.detected=[...new Set([...(d.models||[]),...editor.detected])];(d.models||[]).forEach((m,i)=>ensureModelMeta(m,i));if(editor.selected.size===0)(d.models||[]).forEach(m=>editor.selected.add(m));renderPicker();$('#discoverStatus').textContent=`Found ${(d.models||[]).length} model(s).`}catch(e){$('#discoverStatus').textContent=e.message;toast(e.message,true)}finally{$('#discoverBtn').disabled=false}};
$('#testProviderBtn').onclick=async()=>{try{const p=readForm();if(!editor.selected.size)throw new Error('Select at least one model');$('#testProviderBtn').disabled=true;$('#testResults').innerHTML='<div class="inline-status">Testing…</div>';const d=await api('/admin/api/provider-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(p))});$('#testResults').innerHTML=(d.results||[]).map(x=>`<div class="test-row ${x.ok?'ok':'fail'}"><strong>${esc(x.model)}</strong><span>${x.ok?'PASS':'FAIL'}</span><span>${x.status_code||'—'}</span><span>${x.latency_ms} ms</span><small>${esc(x.error||'')}</small></div>`).join('');toast(d.ok?'All selected models passed':`${d.passed}/${d.total} models passed`,!d.ok)}catch(e){$('#testResults').innerHTML=`<div class="inline-status badtext">${esc(e.message)}</div>`;toast(e.message,true)}finally{$('#testProviderBtn').disabled=false}};
$('#saveProviderBtn').onclick=async()=>{try{const p=readForm(),b=JSON.stringify(payload(p));$('#saveProviderBtn').disabled=true;if(editor.mode==='add')await api('/admin/api/providers',{method:'POST',headers:{'Content-Type':'application/json'},body:b});else await api('/admin/api/providers/'+encodeURIComponent(editor.originalId),{method:'PUT',headers:{'Content-Type':'application/json'},body:b});toast('Provider saved and runtime reloaded');modal(false);await refresh()}catch(e){toast(e.message,true)}finally{$('#saveProviderBtn').disabled=false}};
$('#deleteProviderBtn').onclick=async()=>{if(!confirm(`Delete provider "${editor.originalId}"?`))return;try{await api('/admin/api/providers/'+encodeURIComponent(editor.originalId),{method:'DELETE'});toast('Provider deleted');modal(false);await refresh()}catch(e){toast(e.message,true)}};
tick();
